### ISSUE TITLE
DustShoe_Rail_Left.STL missing 

### ISSUE THREAD

**Issue by jamesagarside** [RootCNC/Root_4_Lite#1]
The STL for DustShoe_Rail_Left is not contained within this repo.

**Comment by tiberiuichim** [comment]
![image](https://user-images.githubusercontent.com/141568/230763468-ca2447b1-8a9b-4583-9c0f-e7da6a708a49.png)
https://wiki.rootcnc.com/en/Root-4-Lite/Print-Info
